config/routes.rb
Rails.application.routes.draw do
  resources :projects
  # get 'home/index'
  root "home#index"

  get "register", to: "users#new"
  post "users", to: "users#create"

  get "login", to: "users#login"
  post "authenticate", to: "users#authenticate"
  
  delete "logout", to: "users#logout"
  resources :users do
    post :authenticate, on: :collection
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password
	validates :name, presence: true
	validates :email, uniqueness: true, presence: true
	validates :password, length: { minimum: 6 }
	has_many :projects, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user
    private
  
    def current_user
      @current_user ||= User.find_by(id: session[:user_id])
    end
  
    def require_login
      unless current_user
        flash[:error] = "You must be logged in to access this section."
        redirect_to login_path # or wherever you want to redirect the user
      end
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :require_login
  before_action :set_project, only: %i[ show edit update destroy ]

  # GET /projects or /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1 or /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = current_user.projects.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = current_user.projects.build(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to project_url(@project), notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to project_url(@project), notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:name, :description, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :redirect_signed_in_user, only: [:new, :create, :login, :authenticate]
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: "You have successfully registered."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def login
    @user = User.new
  end

  def authenticate
    user = User.find_by(email: params[:user][:email])
    if user && user.authenticate(params[:user][:password])
      session[:user_id] = user.id
      redirect_to root_path, notice: "You have successfully logged in."
    else
      @user = User.new(email: params[:user][:email])
      flash[:error] = "Invalid email or password."
      redirect_to login_path
    end
  end

  def logout
    session[:user_id] = nil
    redirect_to root_path, notice: "You have successfully logged out."
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def redirect_signed_in_user
    if current_user
      redirect_to root_path, alert: "You are already signed in."
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<!-- application.html.erb -->
<% if current_user %>
<%= current_user.email %>
  <h1><%= link_to 'Project', projects_path %></h1>
  <%= button_to "Logout", logout_path, method: :delete %> <br>
<% else %>
  <%= link_to "Login", login_path %>
  <%= link_to "Register", register_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PureAuth</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
<% if flash[:notice] %>
  <div class="alert alert-success"><%= flash[:notice] %></div>
<% elsif flash[:error] %>
  <div class="alert alert-danger"><%= flash[:error] %></div>
<% end %>
    <%= yield %>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_with(model: project) do |form| %>
  <% if project.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% project.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/_project.html.erb
<div id="<%= dom_id project %>">
  <p>
    <strong>Name:</strong>
    <%= project.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= project.description %>
  </p>

  <p>
    <strong>User:</strong>
    <%= project.user_id %>
  </p>

</div>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render "form", project: @project %>

<br>

<div>
  <%= link_to "Show this project", @project %> |
  <%= link_to "Back to projects", projects_path %>
</div>

app/views/projects/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Projects</h1>

<div id="projects">
  <% @projects.each do |project| %>
    <%= render project %>
    <p>
      <%= link_to "Show this project", project %>
    </p>
  <% end %>
</div>

<%= link_to "New project", new_project_path %>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render "form", project: @project %>

<br>

<div>
  <%= link_to "Back to projects", projects_path %>
</div>

app/views/projects/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @project %>

<div>
  <%= link_to "Edit this project", edit_project_path(@project) %> |
  <%= link_to "Back to projects", projects_path %>

  <%= button_to "Destroy this project", @project, method: :delete %>
</div>

app/views/shared/_form_errors.html.erb
<% if object.errors.any? %>
  <div class="bg-pink-100 rounded-lg p-4 md:px-6 mb-4 text-pink-700 text-sm">
    <h2 class="font-semibold mb-3">The form contains <%= pluralize(object.errors.count, "error") %></h2>

    <ul class="list-inside list-disc">
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_notice.html.erb
<% if flash[:notice] %>
  <div class="alert alert-success"><%= flash[:notice] %></div>
<% elsif flash[:error] %>
  <div class="alert alert-danger"><%= flash[:error] %></div>
<% end %>

app/views/users/login.html.erb
<!-- login.html.erb -->
<h1>Login</h1>
<%= form_for @user, url: authenticate_users_path do |f| %>
  <%= f.label :email %>
  <%= f.email_field :email, required: true %>

  <%= f.label :password %>
  <%= f.password_field :password, required: true %>

  <%= f.submit "Login" %>
<% end %>

app/views/users/new.html.erb
<!-- new.html.erb -->
<h1>Register</h1>
<%= form_for @user, url: users_path do |f| %>
<%= render "shared/form_errors", object: f.object %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true %>

  <%= f.label :email %>
  <%= f.email_field :email, required: true %>

  <%= f.label :password %>
  <%= f.password_field :password, required: true %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, required: true %>

  <%= f.submit "Register" %>
<% end %>